### PR TITLE
Fix Issue with Iphone

### PR DESCRIPTION
**Pull request by a-tonchev**
Fix Issue with Iphone

### CODE REVIEW

**Comment by yifaneye** [comment]
Thank you @a-tonchev for fixing this issue!

**Comment by jedlau** [comment]
Thanks for fixing this issue, @a-tonchev , and for merging, @yifaneye !

Quick question: Before calling `mediaQueryList.removeEventListener()`, I wonder why the check is for `mediaQueryList.addEventListener()`. In other words, instead of this:

`return () => mediaQueryList.addEventListener
      ? mediaQueryList.removeEventListener('change', callback)
      : window.removeEventListener('resize', callback);
`

Maybe it should be this:
`return () => mediaQueryList.removeEventListener
      ? mediaQueryList.removeEventListener('change', callback)
      : window.removeEventListener('resize', callback);
`

Thoughts? Thanks.

**Comment by yifaneye** [comment]
Hi @jedlau !

Thank you for pointing it out! 😀

Before I merged `dev` into `master`, I had the same thoughts as you. So, I made the change before merging `dev` into `master`. The code from v0.2.3 is [here](https://github.com/yifaneye/react-gallery-carousel/blob/2027b76d702ae96c3869ce1df3b2c9e8fe5ca366/src/utils/useMediaQuery.js#L15)

**Comment by jedlau** [comment]
👍

**Comment by a-tonchev** [comment]
@jedlau is right, I must have copy paste mistake :)

**Pull request merged**
